"""Initial migration

Revision ID: b3222a5ac9f4
Revises: 
Create Date: 2024-11-02 17:54:40.441415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3222a5ac9f4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auctions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auction_id', sa.String(), nullable=True),
    sa.Column('marketplace', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('current_bid', sa.Float(), nullable=True),
    sa.Column('total_units', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('retail_value', sa.Float(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('shipping_cost', sa.Float(), nullable=True),
    sa.Column('total_bids', sa.Integer(), nullable=True),
    sa.Column('cost_per_unit', sa.Float(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auctions_auction_id'), 'auctions', ['auction_id'], unique=True)
    op.create_index(op.f('ix_auctions_id'), 'auctions', ['id'], unique=False)
    op.create_index(op.f('ix_auctions_marketplace'), 'auctions', ['marketplace'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auctions_marketplace'), table_name='auctions')
    op.drop_index(op.f('ix_auctions_id'), table_name='auctions')
    op.drop_index(op.f('ix_auctions_auction_id'), table_name='auctions')
    op.drop_table('auctions')
    # ### end Alembic commands ###
